""" A series of helper functions and constants related to rendering """

SCREEN_WIDTH = 80
SCREEN_HEIGHT = 50

CAMERA_WIDTH = SCREEN_WIDTH
CAMERA_HEIGHT = SCREEN_HEIGHT

WORLD_WIDTH = 100
WORLD_HEIGHT = 100

CHUNK_WIDTH = 20
CHUNK_HEIGHT = 20